-- Create the admin user with the specific credentials
-- This inserts the user directly into auth.users table
INSERT INTO auth.users (
  id,
  instance_id,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmed_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'chetanrajjakanur2002@gmail.com',
  crypt('/Raja_2002\', gen_salt('bf')),
  now(),
  now(),
  '',
  now(),
  '',
  null,
  '',
  '',
  null,
  null,
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"CHETANRAJ JAKANUR"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  now(),
  '',
  0,
  null,
  '',
  null,
  false,
  null
) ON CONFLICT (email) DO NOTHING;

-- Insert admin profile data
INSERT INTO admin_profiles (
  user_id,
  full_name,
  email,
  title,
  bio,
  phone,
  location,
  linkedin_url,
  github_url,
  resume_url,
  profile_image_url
) 
SELECT 
  auth.users.id,
  'CHETANRAJ JAKANUR',
  'chetanrajjakanur2002@gmail.com',
  'Full Stack Developer — Cloud Engineer — Database Engineer',
  'Proficient Full Stack Developer with hands-on experience in building dynamic web applications using MERN stack, Flask, and Flutter. Skilled in integrating AI/ML models, real-time data systems, and cloud-based services to deliver scalable, user-centric solutions.',
  '7022929504',
  'Bengaluru, Karnataka, India',
  'https://www.linkedin.com/in/chetanraj-jakanur-1425451b4/',
  'https://github.com/chetanraj-2002',
  '/ChetanrajJakanur_Resume.pdf',
  '/src/assets/chetanraj-profile.jpg'
FROM auth.users 
WHERE email = 'chetanrajjakanur2002@gmail.com'
ON CONFLICT (user_id) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  email = EXCLUDED.email,
  title = EXCLUDED.title,
  bio = EXCLUDED.bio,
  phone = EXCLUDED.phone,
  location = EXCLUDED.location,
  linkedin_url = EXCLUDED.linkedin_url,
  github_url = EXCLUDED.github_url,
  resume_url = EXCLUDED.resume_url,
  profile_image_url = EXCLUDED.profile_image_url;