// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adkuvgyyurjzqmwwwvkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFka3V2Z3l5dXJqenFtd3d3dmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTAwMTIsImV4cCI6MjA3MzMyNjAxMn0.Ct4NS9YRq_hW2u3o_wNUGZOQsLDM5XYZeO1fEioghQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});